server:
  port: 8081


spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


jwt:
  secret: ${JWT_SECRET}
  expiryMs: 3600000 # 1 hour

logging:
  level:
    root: INFO
    com.rideshare.auth_service: DEBUG


    #TWILIO CONFIGRATION
twilio:
  account.sid: ${TWILIO_ACCOUNT_SID}
  auth.token: ${TWILIO_AUTH_TOKEN}
  from.number: ${TWILIO_PHONE_NUMBER}


  #OTP CONFIGURATION
otp:
    expiry.seconds: 300 # 5 minutes
    verified.expiry.seconds: 600 # 10 minutes
    resend.cooldown.seconds: 60 # 1 minute


#Eureka Client Configration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
debug: true
