server:
  port: 8081


spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/auth_service_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:ishan123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


jwt:
  secret: ${JWT_SECRET:zAsDlPnHeZTUd2e9OXG6l7z8kl+4pqFKGf6h9O6e92I=}
  expiryMs: 3600000 # 1 hour

logging:
  level:
    root: INFO
    com.rideshare.auth_service: DEBUG


    #TWILIO CONFIGRATION
twilio:
  account.sid: ${TWILIO_ACCOUNT_SID:ACf266c4681593eb5947bb2f6bcb8d9bf8}
  auth.token: ${TWILIO_AUTH_TOKEN:ad478b7658d1f507c447f34f01558fbb}
  from.number: ${TWILIO_PHONE_NUMBER:+18203467202}


  #OTP CONFIGURATION
otp:
    expiry.seconds: 300 # 5 minutes
    verified.expiry.seconds: 600 # 10 minutes
    resend.cooldown.seconds: 60 # 1 minute


#Eureka Client Configration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
debug: true
