server:
  port: 8081


spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiry-ms: 3600000 # 1 hour

logging:
  level:
    root: INFO
    com.rideshare.auth_service: DEBUG


    #TWILIO CONFIGRATION
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  from-number: ${TWILIO_FROM_NUMBER}


  #OTP CONFIGURATION
otp:
    expiry-seconds: 300 # 5 minutes
    verified-expiry-seconds: 600 # 10 minutes
    resend-cooldown-seconds: 60 # 1 minute

debug: true
